[package]
name = "nlpmodels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
rust-bert = "0.20.0"
serde = { version = "1.0.130", features = ["derive"] }
